version: '3.8'

services:
    frontend: 
      build: ./frontend
      ports: 
        - "3000:3000"
      depends_on:
        - backend

    backend:
      build: ./backend
      ports: 
        - "8000:8000"
      environment:
        - DATABASE_URL=postgres://todo_user:todo_password@db/todoapp
      depends_on:
        - db

    db: 
      image: postgres
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment: 
        POSTGRES_DB: todoapp
        POSTGRES_USER: todo_user
        POSTGRES_PASSWORD: todo_password

volumes:
  pgdata: